apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jdotw.github.io/jk8s
    chart: canary-rollout
    targetRevision: "1.0.1"
    helm:
      releaseName: inventory
      values: |
        {{ toYaml .Values.inventory | nindent 8 }}
  destination:
    namespace: "{{ .Values.argocd.namespace }}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
