apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrape
  namespace: "{{ .Values.argocd.namespace }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jdotw.github.io/jk8s
    chart: canary-rollout
    targetRevision: "1.0.14"
    helm:
      releaseName: scrape
      values: |
        {{ toYaml .Values.scrape | nindent 8 }}
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
