platform:
  dns:
    fqdn: ${FQDN}
    externalDNS:
      enabled: true
      zoneID: ${ZONE_ID}
      aws:
        serviceAccountName: external-dns
  tls:
    certManager:
      enabled: true
      email: admin@${FQDN}
      aws:
        serviceAccountName: cert-manager
      selfSigned:
        enabled: false
      letsEncrypt:
        staging:
          enabled: true
          email: admin@${FQDN}
          route53:
            zoneID: ${ZONE_ID}
  secrets:
    externalSecrets:
      enabled: true
      rdsSecretName: ${RDS_SECRET}
      aws:
        secretsManager:
          argocdServiceAccountName: external-secrets
          jaegerServiceAccountName: external-secrets
          appServiceAccountName: external-secrets
          crossplaneServiceAccountName: external-secrets
  telemetry:
    jaeger:
      storage:
        es:
          enabled: true
          url: https://${ES_DOMAIN_ENDPOINT}
          credentialsSecretName: ${ES_SECRET}
        inMemory:
          enabled: false
  rds:
    host: ${RDS_HOST}
  apps: 
    - name: master-app
      repoURL: https://github.com/jdotw/isvanilla.git
      targetRevision: HEAD
      path: argocd/master-app