inventory:
  app:
    name: "inventory"
    extraEnv:
      - name: AUTH0_DOMAIN
        value: "isvanilla.au.auth0.com"
    image: 132602212048.dkr.ecr.ap-southeast-2.amazonaws.com/inventory:a2cb04c63e87c7f1095a4407af6327fe0027e204
  virtualService:
    hosts:
      - api.syrupstock.com
  db:
    name: isvanilla
    migrations:
      image: 132602212048.dkr.ecr.ap-southeast-2.amazonaws.com/migrate:latest
      repoURL: https://github.com/jdotw/isvanilla.git
      path: backend/db/migrations
scrape:
  app:
    name: "scrape"
    extraEnv:
      - name: AUTH0_DOMAIN
        value: "isvanilla.au.auth0.com"
    image: 132602212048.dkr.ecr.ap-southeast-2.amazonaws.com/scrape:2bc2b648beb951072ee573b14fd15745fd06c8e1
    replicas: 1
  virtualService:
    hosts:
      - api.syrupstock.com
argocd:
  namespace: ""