---
apiVersion: v1
kind: Service
metadata:
  name: app-rollout-canary-stable
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-rollout-canary
---
apiVersion: v1
kind: Service
metadata:
  name: app-rollout-canary
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-rollout-canary
