apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-migration
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  config.yaml: |
    production:
      dialect: postgres
      datasource: dbname={{ .Values.db.name }} sslmode={{ .Values.db.sslmode }}
      dir: backend/db/migrations
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sql-migration
  labels: {}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "migration-job-pod"
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrations
          image: "{{ .Values.registry }}/migrate:latest"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
                git clone --single-branch --branch main {{ .Values.repoURL }} &&
                cd isvanilla &&
                ls -al backend &&
                cat /config/config.yaml &&
                /bin/sql-migrate up -config=/config/config.yaml -env="{{ .Values.environment }} -dryrun"
          envFrom:
            - secretRef: 
                name: rds
          volumeMounts:
            - name: sql-migration
              mountPath: "/config/config.yaml"
              subPath: "config.yaml"
              readOnly: true
      volumes:
        - name: sql-migration
          configMap:
            name: sql-migration
            items:
            - key: "config.yaml"
              path: "config.yaml"