---
apiVersion: v1
kind: Service
metadata:
  name: inventory-rollout-stable
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: inventory-rollout
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-rollout
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: inventory-rollout
