# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: inventory-rollout-kube
#   labels:
#     app.kubernetes.io/name: applications.argoproj.io
#     app.kubernetes.io/part-of: argocd
#     app.kubernetes.io/instance: argocd
#     app.kubernetes.io/managed-by: Tiller
#   annotations:
#     kubernetes.io/ingress.class: "ingressgateway"
#     kubernetes.io/ingress.tld: "flo.pub"
# spec:
#   selector:
#     istio: ingressgateway
#   servers:
#     - port:
#         number: 80
#         name: http
#         protocol: HTTP
#       hosts:
#         - "inventory-rollout.kube"
# ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-rollout-vs
  labels:
    app.kubernetes.io/name: applications.argoproj.io
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Tiller
spec:
  hosts:
    - "{{ .Values.fqdn }}"
  gateways:
    - istio-ingress/ingress-gateway
  http:
    - name: primary
      route:
        - destination:
            host: inventory-rollout-stable
          weight: 100
        - destination:
            host: inventory-rollout
          weight: 0
