// DO NOT EDIT
// This file was code-generated by github.com/jdotw/oapi-gokit-codegen version (devel)
// It is expected that this file will be re-generated and overwitten to
// adapt to changes in the OpenAPI spec that was used to generate it

package inventory

import (
	"bytes"
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/jdotw/oapi-gokit-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetInventorySnapshots request
	GetInventorySnapshots(ctx context.Context, vendorID string, productID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateInventorySnapshot request with any body
	CreateInventorySnapshotWithBody(ctx context.Context, vendorID string, productID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateInventorySnapshot(ctx context.Context, vendorID string, productID string, inventorySnapshot InventorySnapshot, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetInventorySnapshots(ctx context.Context, vendorID string, productID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInventorySnapshotsRequest(c.Server, vendorID, productID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInventorySnapshotWithBody(ctx context.Context, vendorID string, productID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInventorySnapshotRequestWithBody(c.Server, vendorID, productID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInventorySnapshot(ctx context.Context, vendorID string, productID string, inventorySnapshot InventorySnapshot, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInventorySnapshotRequest(c.Server, vendorID, productID, inventorySnapshot)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetInventorySnapshotsRequest generates requests for GetInventorySnapshots
func NewGetInventorySnapshotsRequest(server string, vendorID string, productID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "vendor_id", runtime.ParamLocationPath, vendorID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "product_id", runtime.ParamLocationPath, productID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vendor/%s/product/%s/inventory", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateInventorySnapshotRequest calls the generic CreateInventorySnapshot builder with application/json body
func NewCreateInventorySnapshotRequest(server string, vendorID string, productID string, inventorySnapshot InventorySnapshot) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(inventorySnapshot)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateInventorySnapshotRequestWithBody(server, vendorID, productID, "application/json", bodyReader)
}

// NewCreateInventorySnapshotRequestWithBody generates requests for CreateInventorySnapshot with any type of body
func NewCreateInventorySnapshotRequestWithBody(server string, vendorID string, productID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "vendor_id", runtime.ParamLocationPath, vendorID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "product_id", runtime.ParamLocationPath, productID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vendor/%s/product/%s/inventory", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetInventorySnapshots request
	GetInventorySnapshotsWithResponse(ctx context.Context, vendorID string, productID string, reqEditors ...RequestEditorFn) (*GetInventorySnapshotsResponse, error)

	// CreateInventorySnapshot request with any body
	CreateInventorySnapshotWithBodyWithResponse(ctx context.Context, vendorID string, productID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInventorySnapshotResponse, error)

	CreateInventorySnapshotWithResponse(ctx context.Context, vendorID string, productID string, inventorySnapshot InventorySnapshot, reqEditors ...RequestEditorFn) (*CreateInventorySnapshotResponse, error)
}

type GetInventorySnapshotsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]InventorySnapshot
	JSON400      *HTTPError
	JSON500      *HTTPError
}

// Status returns HTTPResponse.Status
func (r GetInventorySnapshotsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInventorySnapshotsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateInventorySnapshotResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InventorySnapshot
	JSON400      *HTTPError
	JSON401      *HTTPError
	JSON403      *HTTPError
	JSON500      *HTTPError
}

// Status returns HTTPResponse.Status
func (r CreateInventorySnapshotResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateInventorySnapshotResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetInventorySnapshotsWithResponse request returning *GetInventorySnapshotsResponse
func (c *ClientWithResponses) GetInventorySnapshotsWithResponse(ctx context.Context, vendorID string, productID string, reqEditors ...RequestEditorFn) (*GetInventorySnapshotsResponse, error) {
	rsp, err := c.GetInventorySnapshots(ctx, vendorID, productID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInventorySnapshotsResponse(rsp)
}

// CreateInventorySnapshotWithBodyWithResponse request with arbitrary body returning *CreateInventorySnapshotResponse
func (c *ClientWithResponses) CreateInventorySnapshotWithBodyWithResponse(ctx context.Context, vendorID string, productID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInventorySnapshotResponse, error) {
	rsp, err := c.CreateInventorySnapshotWithBody(ctx, vendorID, productID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInventorySnapshotResponse(rsp)
}

func (c *ClientWithResponses) CreateInventorySnapshotWithResponse(ctx context.Context, vendorID string, productID string, inventorySnapshot InventorySnapshot, reqEditors ...RequestEditorFn) (*CreateInventorySnapshotResponse, error) {
	rsp, err := c.CreateInventorySnapshot(ctx, vendorID, productID, inventorySnapshot, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInventorySnapshotResponse(rsp)
}

// ParseGetInventorySnapshotsResponse parses an HTTP response from a GetInventorySnapshotsWithResponse call
func ParseGetInventorySnapshotsResponse(rsp *http.Response) (*GetInventorySnapshotsResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInventorySnapshotsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []InventorySnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateInventorySnapshotResponse parses an HTTP response from a CreateInventorySnapshotWithResponse call
func ParseCreateInventorySnapshotResponse(rsp *http.Response) (*CreateInventorySnapshotResponse, error) {
	bodyBytes, err := ioutil.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateInventorySnapshotResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InventorySnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest HTTPError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
