on:
  push:
    branches: 
      - main

name: Build and Publish to ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        INVENTORY_IMAGE_TAG: ${{ github.sha }}
        SCRAPE_REPOSITORY: scrape
        SCRAPE_IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build Inventory docker container and push it to ECR 
        echo "Building Inventory image"
        docker build -t $ECR_REGISTRY/inventory:$INVENTORY_IMAGE_TAG -f docker/inventory/Dockerfile .
        echo "Pushing Inventory image to ECR..."
        docker push $ECR_REGISTRY/inventory:$INVENTORY_IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/inventory:$INVENTORY_IMAGE_TAG"
        # Build Scrape docker container and push it to ECR 
        echo "Building Scrape image"
        docker build -t $ECR_REGISTRY/scrape:$INVENTORY_IMAGE_TAG -f docker/scrape/Dockerfile .
        echo "Pushing Scrape image to ECR..."
        docker push $ECR_REGISTRY/scrape:$INVENTORY_IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/scrape:$INVENTORY_IMAGE_TAG"
        # Build Inventory docker container and push it to ECR 
        echo "Building Migrate image"
        docker build -t $ECR_REGISTRY/migrate:$INVENTORY_IMAGE_TAG -f docker/migrate/Dockerfile .
        echo "Pushing Migrate image to ECR..."
        docker push $ECR_REGISTRY/migrate:$INVENTORY_IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/migrate:$INVENTORY_IMAGE_TAG"
